name: flutter_deep_speech_example
description: Demonstrates how to use the flutter_deep_speech plugin.

publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  flutter_deep_speech:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/models/